### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by lemairecarl** [oxpig/SCALOP#2]
* I installed numpy and pandas (in a virtualenv)
* I installed hmmer (configure, make, make install)
* I ran `python setup.py install`

Then, here is what I get when I try to import scalop:

```
(env) $ python
Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scalop.predict import assign
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/carl/source/SCALOP/env/lib/python3.8/site-packages/scalop/predict.py", line 5, in <module>
    from .anarci import run_anarci
  File "/home/carl/source/SCALOP/env/lib/python3.8/site-packages/scalop/anarci/__init__.py", line 3, in <module>
    from .anarci import *
  File "/home/carl/source/SCALOP/env/lib/python3.8/site-packages/scalop/anarci/anarci.py", line 65, in <module>
    from Bio.SearchIO.HmmerIO import Hmmer3TextParser as HMMERParser
ModuleNotFoundError: No module named 'Bio'
```

The `SCALOP` command line also causes an error:

```
(env) $ SCALOP
bash: /home/carl/source/SCALOP/env/bin/SCALOP: /bin/python3: bad interpreter: No such file or directory
```

This might be related to using a virtualenv.
Can you shared more precise steps on how you're able to install?

**Comment by lemairecarl** [comment]
Ok I found the solution for the first issue (`ModuleNotFoundError: No module named 'Bio'`). I needed to install biopython. It's not obvious. It should be added to the dependencies. Even better, there should be a requirements.txt, containing:

```
numpy
pandas
biopython
```

As for the other issue, I managed to get it to work inside a container. That was a pain.

**Comment by broncio123** [comment]
Updated README file with tested conda-based installation instructions.
